version: '3'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: luizfmbrizola
      POSTGRES_PASSWORD: brizola2031
      POSTGRES_DB: IMC-banco